site_name: Courtade Lab Docs
site_url: http://folk.ntnu.no/courtade
nav:
    - Home: index.md
    - HPC Protocols: hpc.md
theme: readthedocs

plugins:
    - encryptcontent:
        global_password: 'your_password'