site_name: Courtade Lab Docs
site_url: http://folk.ntnu.no/courtade
nav:
    - Home: index.md
    - HPC Protocols: hpc.md
theme: readthedocs

plugins:
    - encryptcontent:
        use_secret: 'ENCRYPTCONTENT_PASSWORD'
        remember_password: True
        default_expire_delay: 24   # <-- Default expire delay in hours (optional)