name: Build MKdocs site

on:
  push

jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: gcourtade/mkdocs-build-action@master

    - name: Commit & Push changes
      run: |
        git commit -am "Automated commit"
        git push


