name: Build MKdocs site

on:
  push
permissions:
  contents: write
  
jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
 

    - name: Build
      uses: gcourtade/mkdocs-build-action@master

    - name: Commit & Push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        git add -A
        git commit -m "Automated commit"
        git push


