name: Build MKdocs site

on:
  push

jobs:
  mkdocs:
    name: Build and deploy mkdocs site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: jnanadarshan/mkdocs-build-action@v0.24
